name: C/C++ CI

on:
  push:
    branches: [ "CI_test" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name:  Build core
      run: cmake -B core/build -S core && cmake --build core/build
    - name: Build Tcp
      run: cmake -B TCP/build -S TCP && cmake --build TCP/build
    - name: Build GUI
      run: dotnet build GUI/RayTracerGUI/
